# Generated by Django 5.2 on 2025-04-28 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_kanbancard_title_kanbancard_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanCardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kanbancard')),
            ],
        ),
    ]
