# Generated by Django 5.2 on 2025-04-28 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_kanbancardimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancard',
            name='column',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.kanbancolumn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kanbancolumn',
            name='board',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.kanbanboard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kanbanboard',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kanbantype'),
        ),
    ]
