# Generated by Django 5.2 on 2025-04-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_kanbancard_column_kanbancolumn_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbantype',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
