# Generated by Django 5.2 on 2025-04-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_kanbantype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanbancard',
            name='tags',
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='tag',
            field=models.ManyToManyField(to='api.kanbancardtag'),
        ),
        migrations.AlterField(
            model_name='kanbancardtag',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
